---
output: github_document
---

# Convert WFS data from the Berlin Geodata Portal "FIS-Broker"

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(glue)
library(httr)
library(sf)
library(dplyr)
```

```{r}

get_url <- function(x) {

    u_data <- glue("http://fbinter.stadt-berlin.de/fb/wfs/data/senstadt/{x}")
    u_geom <- glue("http://fbinter.stadt-berlin.de/fb/wfs/geometry/senstadt/{x}")

    query <- glue("?service=wfs&version=2.0.0&request=GetFeature&TYPENAMES={x}")

    url_data <- paste0(u_data, query)
    url_geom <- paste0(u_geom, query)

    if(!http_error(url_data)) {
       url_data
    } else {
       url_geom
    }

}

get_X_Y_coordinates <- function(s) {
  
  sftype <- unique(as.character(sf::st_geometry_type(s)))

  if(sftype == "POINT") {
    s  <- s %>% 
          sf::st_coordinates() %>% 
          as.data.frame() %>%
          bind_cols(s, .)
      } else {
    s
      }
}

sf_fisbroker <- function(x) {
  
  url <- get_url(x)
  print(url)
  s <- sf::read_sf(url)
  sf::st_crs(s) <- 25833
  s <- sf::st_transform(s, 4326)
  s <- get_X_Y_coordinates(s)
  s

}

export_format <- c(
          "geojson", 
          # "shp",
          "sqlite",
          "xlsx"
   )

sf_save <- function(z, fname) {
  
  ifelse(!dir.exists(fname), dir.create(fname), "Folder exists already")
  ff <- paste(file.path(fname, fname), export_format, sep = ".")
  purrr::walk(ff, ~{ sf::st_write(z, .x, delete_dsn = TRUE)})
  saveRDS(z, paste0(file.path(fname, fname), ".rds"))
  
}

```

# Description

This repository is a proof-of-concept how to convert WFS data into different output formats using "Simple Features" [https://github.com/r-spatial/sf](https://github.com/r-spatial/sf)

## Gebäudealter der Wohnbebauung 2015

```{r}

z <- sf_fisbroker("s06_12baualter")

dplyr::glimpse(z)

sf_save(z, "Gebaeudealter")

```

## Einwohnerdichte 2017

```{r eval = FALSE}

z <- sf_fisbroker("s06_06ewdichte2017")

dplyr::glimpse(z)

sf_save(z, "Einwohnerdichte2017")

```

## Tempolimit

```{r eval = TRUE}

z <- sf_fisbroker("s_vms_tempolimits_spatial")

dplyr::glimpse(z)

sf_save(z, "Tempolimit")

```

## Wohnlagenkarte nach Adressen zum Berliner Mietspiegel 2017


```{r eval = TRUE}

z <- sf_fisbroker("s_wohnlagenadr2017")

z  <- z %>% 
       mutate(ADR_num = as.numeric(stringr::str_extract(ADR, "[0-9]+")), 
              ADR_chr = stringr::str_extract(ADR, "[aA-zZ]+"))

dplyr::glimpse(z)

sf_save(z, "wohnlagenadr2017")

```

## Emissionen

```{r eval = TRUE}

z <- sf_fisbroker("s03_12_2emissionen")

dplyr::glimpse(z)
                             
sf_save(z, "Emissionen")

```
